test_path: "/sise/home/liorkob/moj/resources/data/first_level.csv"
save_directory: /sise/home/ezradin/moj/train_models
logger_directory : "/sise/home/liorkob/moj/resources/data/similarity/docx_Legal-heBERT/"
labels_ :
  - reject
  - CONFESSION
  - CIRCUM_OFFENSE
  - GENERAL_CIRCUM
  - PUNISHMENT

seed: 42
num_samples_list: [50,20,50,50,10]
model_name_initial: test
all_class: true
database_dir: /sise/home/liorkob/moj/resources/data/database/

pretrained_model_list:
      - HeNLP/HeRo

#flows_flag
training: false # Set to 'true' to train the model, and 'false' to skip training.
evaluate: false # Set to 'true' to evaluate the model, and 'false' to skip evaluation.
doc_pipeline: false # Set to 'true' to process doc with prediction,FE,embedding, and 'false' to skip .
doc_dir_pipeline : true
# List of models to train.
# Set the respective model name to 'true' to include it in training, 'false' to exclude.
models_to_train:
  - t-few: false
  - roberta: false
  - setfit: true



param:
  num_labels : 5
  learning_rate: 3e-5
  num_layers: 3
  hidden_size: 128
  dropout: 0.2
  batch_size: 16
  num_iteration: 5
  num_epoch: 5
  pretrained_model : "amberoad/bert-multilingual-passage-reranking-msmarco"

roberta_param:
  - learning_rate: 5e-5
  - data_path: /resources/data/similarity/
  - model_name: RoBERTa binary


setfit_param:
  - learning_rate: 5e-5
  - data_path: /resources/data/similarity/
  - model_name: set fit

loads:
  path_models :  /path/to/models/

model_path : '/sise/home/ezradin/moj/finetuning_models/'
df_path : 'C:/Users/max_b/PycharmProjects/moj_sl/pred-sentencing/resources/data/new_data/train_test/second_lvl/test.csv'

all_labels:
  - CONFESSION
  - CIRCUM_OFFENSE
  - GENERAL_CIRCUM
  - PUNISHMENT
  - CIR_AMMU_AMOUNT_WEP
  - CIR_BUYER_ID_WEP
  - CIR_HELD_WAY_WEP
  - CIR_MONEY_PAID_WEP
  - CIR_OBTAIN_WAY_WEP
  - CIR_PLANNING
  - CIR_PURPOSE
  - CIR_STATUS_WEP
  - CIR_TYPE_WEP
  - CIR_USE
  - CONFESSION_LVL2
  - REGRET
  - RESPO



first_level_labels:
  - reject
  - CONFESSION
  - CIRCUM_OFFENSE
  - GENERAL_CIRCUM
  - PUNISHMENT

second_level_labels:
  - CIR_AMMU_AMOUNT_WEP
  - CIR_BUYER_ID_WEP
  - CIR_HELD_WAY_WEP
  - CIR_MONEY_PAID_WEP
  - CIR_OBTAIN_WAY_WEP
  - CIR_PLANNING
  - CIR_PURPOSE
  - CIR_STATUS_WEP
  - CIR_TYPE_WEP
  - CIR_USE
  - CONFESSION_LVL2
  - REGRET
  - RESPO


thresholds:
  - 'CONFESSION': 0.95
  - 'reject': 0.95
  - 'CONFESSION_LVL2': 0.95
  - 'CIRCUM_OFFENSE': 0.95
  - 'CIR_TYPE_WEP': 0.95
  - 'CIR_HELD_WAY_WEP': 0.95
  - 'CIR_STATUS_WEP': 0.95
  - 'CIR_OBTAIN_WAY_WEP': 0.95
  - 'CIR_AMMU_AMOUNT_WEP': 0.95
  - 'GENERAL_CIRCUM': 0.95
  - 'RESPO': 0.95
  - 'CIR_PURPOSE': 0.95
  - 'REGRET': 0.95
  - 'PUNISHMENT': 0.95
  - 'CIR_PLANNING': 0.95
  - 'CIR_BUYER_ID_WEP': 0.95
  - 'CIR_MONEY_PAID_WEP': 0.95
  - 'CIR_USE': 0.95


