experiment_name: '01_02_real_try'

classifiers_path: /sise/home/tak/moj_models/{domain}/{experiment_name}
eval_path : /home/tak/pred-sentencing/results/evaluations/{domain}/sentence_classification/{experiment_name}
db_path: /home/tak/pred-sentencing/results/db/{domain}
result_path: 'results'

first_level_labels:
  - PUNISHMENT
  - GENERAL_CIRCUM
  - reject

#second level labels
second_level_labels: 
  - CIR_TYPE
  - CIR_AMOUNT
  - CIR_ROLE
  - CIR_EQ

