experiment_name: '03_26_with_f2_try'
model_names: 
  # - bert-multilingual-passage-reranking-msmarco
  - dictabert
  # - heBERT
model_name : dictabert

with_clf : True
ground_truth : False
ground_truth_path: /home/tak/MOJ/resources/data/tagging/weapon/gt/sentence_tagging.csv
threshold_method: F1

classifiers_path: /sise/home/tak/moj_models/weapon/{experiment_name}/
eval_path : /home/tak/MOJ/results/evaluations/weapon/sentence_classification/{experiment_name}
test_set_path: /home/tak/MOJ/resources/data/trainning/sentence_classification/weapon/12cases_in_train
db_path: /home/tak/MOJ/results/db/10k_weapon
result_path: 'results'

first_level_labels:
  - PUNISHMENT
  - GENERAL_CIRCUM
  - CIRCUM_OFFENSE
  # - reject
  # - REGRET

  
second_level_labels:
  - CIR_STATUS_WEP
  - CIR_HELD_WAY_WEP
  - CIR_PURPOSE
  - CIR_AMMU_AMOUNT_WEP
  - CIR_OBTAIN_WAY_WEP
  - CIR_TYPE_WEP
  - CIR_USE
  - CIR_PLANNING
  - RESPO
  - REGRET
  - CONFESSION

  
