experiment_name: '03_19_with_f2_try'
model_name: bert-multilingual-passage-reranking-msmarco  # bert-multilingual-passage-reranking-msmarco | heBERT | dictabert
with_clf : False

classifiers_path: /sise/home/tak/moj_models/drugs/{experiment_name}/
eval_path : /home/tak/MOJ/results/evaluations/drugs/sentence_classification/{experiment_name}
test_set_path: /home/tak/MOJ/resources/data/trainning/sentence_classification/drugs/stratify_sentences_50_40_10
db_path: /home/tak/MOJ/results/db/drugs
result_path: 'results'

first_level_labels:
  - CONFESSION
  - CIR_PUNISHMENT
  - GENERAL_CIRCUM
  - CIRCUM_OFFENSE
  # - reject

#second level labels
second_level_labels: 
  - CIR_TYPE
  - CIR_AMOUNT
  - CIR_ROLE
  - CIR_EQ
  # - REGRET
  # - RESPO

