experiment_name: '03_19_with_f2_try'
model_name: bert-multilingual-passage-reranking-msmarco  # bert-multilingual-passage-reranking-msmarco | heBERT | dictabert
with_clf : True

classifiers_path: /sise/home/tak/moj_models/weapon/{experiment_name}/
eval_path : /home/tak/MOJ/results/evaluations/weapon/sentence_classification/{experiment_name}
test_set_path: /home/tak/MOJ/resources/data/trainning/sentence_classification/weapon/stratify_sentences_50_40_10
db_path: /home/tak/MOJ/results/db/weapon
result_path: 'results'

first_level_labels:
  - PUNISHMENT
  - GENERAL_CIRCUM
  # - reject
  - CONFESSION
  - REGRET

  
second_level_labels:
  - CIR_STATUS_WEP
  - CIR_HELD_WAY_WEP
  - CIR_PURPOSE
  - CIR_AMMU_AMOUNT_WEP
  - CIR_OBTAIN_WAY_WEP
  - CIR_TYPE_WEP
  - CIR_USE
  - CIR_PLANNING
  # - RESPO
  # - REGRET
