experiment_inputs:
  model_name: "Decision_Tree_Metrics_features_embd_qa_F1_0.738.pkl"
  query_document: "/sise/home/liorkob/moj/resources/data/verdicts_docx/10096-07-19.docx"
  corpus_dir: "/sise/home/liorkob/moj/resources/new_docx_database/2017_cases_v3/"
  extract_method: 'qa'
experiment_components:

  classifiers:
    classifiers_path: "/sise/home/ezradin/moj/finetuning_models/"
    classifiers_params:

      first_level_labels:
        - reject
        - CONFESSION
        - CIRCUM_OFFENSE
        - GENERAL_CIRCUM
        - PUNISHMENT
      second_level_labels:
        - CIR_AMMU_AMOUNT_WEP
        - CIR_BUYER_ID_WEP
        - CIR_HELD_WAY_WEP
        - CIR_MONEY_PAID_WEP
        - CIR_OBTAIN_WAY_WEP
        - CIR_PLANNING
        - CIR_PURPOSE
        - CIR_STATUS_WEP
        - CIR_TYPE_WEP
        - CIR_USE
        - CONFESSION_LVL2
        - REGRET
        - RESPO
      thresholds:
        - 'CONFESSION': 0.95
        - 'reject': 0.95
        - 'CONFESSION_LVL2': 0.95
        - 'CIRCUM_OFFENSE': 0.95
        - 'CIR_TYPE_WEP': 0.95
        - 'CIR_HELD_WAY_WEP': 0.95
        - 'CIR_STATUS_WEP': 0.95
        - 'CIR_OBTAIN_WAY_WEP': 0.95
        - 'CIR_AMMU_AMOUNT_WEP': 0.95
        - 'GENERAL_CIRCUM': 0.95
        - 'RESPO': 0.95
        - 'CIR_PURPOSE': 0.95
        - 'REGRET': 0.95
        - 'PUNISHMENT': 0.95
        - 'CIR_PLANNING': 0.95
        - 'CIR_BUYER_ID_WEP': 0.95
        - 'CIR_MONEY_PAID_WEP': 0.95
        - 'CIR_USE': 0.95