result_path: results
prediction_dfs: /home/tak/MOJ/results/db/drugs
output_path: /home/tak/MOJ/results/evaluations/drugs/features_extraction
metadata_path: /home/tak/MOJ/resources/data/tagging/drugs/gt/one_defendant_new_.csv